sugarlabs/www-v2

LICENSE
=> Adding GPL v3 License

README.md, docs/CONTRIBUTING.md, docs/dev_guide.md
Adding guide for new contributors
=> Add documentation

.eslintrc.js, .markdownlint.json, .prettierignore, .prettierrc, package-lock.json, package.json
=> Add linting

.github/ISSUE_TEMPLATE/bug_report.md
---
name: Spacing issue in bug_report.md
about: There was a space missing in the bug_report.md.
---
There was a space missing in the bug_report.md. So I have added the space to make it correct.
PR fixes: #41 
change in line 56. Space has been added after 
- Change 1: line 56 space has been added.
- ...
---
=> fixed spacing issue in template

src/components/TryCard.tsx
> ##  Try Button Alignment
>  Fixing buttons alignment in Try section
> ## Description
> I fixed the horizontal alignment of buttons which seemed to be a design issue.
> 
> ## Related Issue
> This PR fixes #46
> 
> ## Changes Made
> * Added flex-1/3 for h3,p and button elements.
> 
> ## Checklist
> * [x]  I have tested these changes locally and they work as expected.
> * [ ]  I have added/updated tests that prove the effectiveness of these changes.
> * [ ]  I have updated the documentation to reflect these changes, if applicable.
> * [x]  I have followed the project's coding style guidelines.
> * [ ]  I have addressed the code review feedback from the previous submission, if applicable.
> 
> ![Screenshot 2025-03-17 121024](https://private-user-images.githubusercontent.com/83063386/42334325 …
=> Fixed Button Alignment

src/components/Testimonials.tsx
---
name: Testimonial Card Alignment
about: Focus on the consistency of spacing, alignment, and overall layout
---
Aligned all testimonial card details to ensure a consistent and cohesive design across components. This improves visual uniformity, readability, and user experience
This PR fixes  [#55](https://github.com/sugarlabs/www-v2/issues/55)
- Changes on Testimonial.tsx file
**Design after changes**
=> Fix Testimonial Card Alignment

src/components/TryCard.tsx
---
About: I have made changes to TryCard.jsx to make the contents of the card align well, keeping the design more consistent.
---
I have made changes to TryCard.jsx to make the contents of the card align well, keeping the design more consistent.
Before:
After:
This PR fixes #61 
- Change 1: added flex to align it properly.
- 
- Tested on local computer
- Used developer tools to test responsiveness
- Tested on Opera GX, Edge and Chrome Browsers.
=> Fixed alignment issues in TryCard.jsx

src/components/DeveloperLinks.tsx, src/components/DeveloperTestimonials.tsx, src/pages/Donate.tsx, src/pages/JoinDevelopment.tsx, src/pages/Products.tsx, src/pages/TryNow/MusicBlocks.tsx, src/pages/TryNow/Sugarizer.tsx, src/pages/TryNow/TurtleBlocks.tsx, src/pages/Volunteer.tsx, src/styles/Animations.ts
1) Z-indexing floating SVGs
2) Making sure ANIMATIONS are on each page.
=> Z indexed and percentage widthing

src/components/DeveloperTestimonials.tsx
---
name: Fixed the logical error so if there are only two cards they will still render.
---
Fixed the logical error so if there are only two cards they will still render.
This PR fixes #68 
- Tested on my laptop.
- Tested on browsers Opera GX, Chrome and Edge
- ...
=> fixed the issue of less than two testimonials

src/constants/Footer.ts
---
name: Corrected the mailing list link
---
In this PR I have replaced the mailing link with the suggested link by @FirePheonix in the path src\constants\Footer.ts
This PR fixes #91 
- replaced the link to https://buttondown.com/sugarlabs in src\constants\Footer.ts
- Ran development server on PC
- Tested on mobile
- Tested on browsers Opera GX, Edge.
- ...
Hey, so I have fixed the link. You can let me know what are the other changes to be made as it is not decided yet and I will commit to the same PR.
=> Corrected mailing list link

package-lock.json, package.json
---
name: Upgrade Vite to 6.2.3 or later
about: Upgraded Vite to the latest version and verified functionality.
---
Upgraded Vite from version **6.2.0** to **6.2.4**.
Fixes #96  
Installed latest version of vite and verified compatibility with plugins and dependencies. 
Ran `npm run build` and `npm run dev` to ensure everything works correctly
- Verified that the development server (`npm run dev`) runs without errors
Please Rectify or do let me know if any thing better can be done .
=> chore: Upgraded vite to 6.2.4

src/components/Product.tsx, src/components/TryNow/StepsToUse.tsx
- Fixes: #95 
https://github.com/user-attachments/assets/45d3f9dd-5deb-46c8-8866-de06cf2b90c0
=> Carousels Changed

src/constants/Testimonials.ts
Added real data to Words of Appreciation in Testimonials Section. I searched the internet for quotes from developers about Sugar Labs, and found data on Medium and LinkedIn.
This PR fixes #82 
Tested in my local machine in Chrome and Arc browsers.
=> feat: add real data to words of appreciation

src/constants/MarkdownFiles/posts/2025-03-24-annual-report-2024.md
on to @sa-fw-an to make carousels for renering HTML components of this annual report.
=> added data for annual report

src/pages/TryNow/MusicBlocks.tsx
=> fix-ui-bug: fixed spacing error

src/components/Try.tsx, src/components/TryCard.tsx, src/constants/TryCardData.ts
=> v3 and v4 added

src/constants/Banner.ts
Replaces mock data with more relevant data.
This PR fixes #81 
I changed all the mock text and deleted examples that were unnecessary.
- It ran on my computer just fine by following documentation steps.
- The one issue I ran into was using the word "we've". It failed because of the apostrophe. I fixed it by replacing a plain-text apostrophe with `’`
We can get more creative later.
---
=> Quick updates to banner data

src/pages/Volunteer.tsx
---
name: Rendering Links
about: Fetched Email And Contact Link from Constants
---
I have used find method on array of objects and search for name with mailing and matrix 
then I have rendered it on Volunteer Page. In case it Doesn't rendered I have provided Defualt value of matrix and mail
This PR fixes #106
- I was asked for the Simpler Complexity and the constant of Volunteer can be easily handled with find method
- Tested this Changes Locally.
=> Rendering Link on Volunteer Page

src/constants/aboutUs/goals.ts, src/constants/aboutUs/mission.ts, src/constants/aboutUs/principles.ts, src/constants/aboutUs/projects.ts, src/constants/aboutUs/roadmap.ts
Quick updates to about us page.
This PR fixes #25 
- modified:   src/constants/aboutUs/goals.ts
- modified:   src/constants/aboutUs/mission.ts
- modified:   src/constants/aboutUs/principles.ts
- modified:   src/constants/aboutUs/projects.ts
- modified:   src/constants/aboutUs/roadmap.ts
Tested on my machine.
---
=> Update about page

src/components/Testimonials.tsx
---
---
Fixes the visual glitch in the Testimonials section where gradient overlays on the left and right sides cut off the testimonial content while scrolling. Adjusted the gradient implementation to ensure smoother visibility.
This PR fixes #129 
- Updated `Testimonials.tsx` to clean up gradient overlay divs.
- Removed unnecessary background class that was causing visual artifacts.
- Ensured the gradient effect is smooth and doesn't cover content.
- Visually tested the carousel to ensure content is no longer obscured.
- Confirmed that gradient fades are now subtle and non-intrusive.
- Ran `npm run lint:ts` and `npm run build` successfully.
The fix is purely visual — no functionality changed. Let me know if …
=> fix(testimonials): adjust gradient overlay to prevent content cutoff

src/components/DeveloperLinks.tsx, src/pages/JoinDevelopment.tsx
---
---
<>Improved the animation for 'Important Links for Developers' section on the Join Development page for a smoother and more consistent visual experience.
<>This PR enhances the visual experience by improving the animation of the section on the "Join Development" page. The smoother transitions make the UI feel more polished and responsive.
This PR fixes  #116
- Adjusted CSS transition timing for fade-in animation using motion div.
- Introduced a grid layout for the links to make all the links appear same time in the screen.
-Added a new Getting Involved section with a card layout, linking to important contributor resources.
- Tested changes locally using `npm run dev`.
- Verified smooth animation on …
=> improvement: Important Links for Developers animation improvement (fixes #116)

src/constants/TryNowData/raspberryPiData.ts
---
---
I updated the quote to be more relevant to what we do at Sugar Labs.
This addresses, but does not completely fix, https://github.com/sugarlabs/www-v2/issues/85
We should have @drLite35 and @44yu5h review the www.sugarlabs.org/raspberry page as well.
I ran ts and linting tests.
=> Update quote, but still need review from RPi dev

src/components/DeveloperTestimonials.tsx, src/constants/VolunteerAndDev/DeveloperTestimonials.ts
Updates to language on Development page, including edits to developer testimonials.
This PR addresses https://github.com/sugarlabs/www-v2/issues/88
Text changed in pullout quote and edits to testimonials.
TS and MD Linting tests have been run.
=> Updates to developer page and its testimonials

src/constants/VolunteerAndDev/DeveloperTestimonials.ts
I added a few more contributor testimonials as requested.
This PR fixes https://github.com/sugarlabs/www-v2/issues/88
I tested with npm run dev; I delinted with npm run format
=> Add a few more testimonials

src/constants/MarkdownFiles/posts/2025-05-12-Role-of-generative-AI-in-education.md
---
Added an upcoming event: Role of Gen ai in education by Ken Kahn on 2025-5-18
---
Updated events page
Added `2025-05-12-Role-of-generative-AI-in-education.md` 
Everything works:
=> Added an upcoming event on 2025-5-18

src/constants/MarkdownFiles/posts/2025-05-12-Role-of-generative-AI-in-education.md
This fixes the date to the correct date for today's event.
=> Correct the date of the event on the event feed

src/constants/MarkdownFiles/posts/2025-05-12-Role-of-generative-AI-in-education.md
=> Fix date in one more spot

docs/GSoC-Blogpost-Guidelines.md, src/constants/MarkdownFiles/posts/GSoC_Template.md
Adding a new GSoC template for Contributors.
=> Add GSoC Template 

src/constants/Header.ts, src/pages/Products.tsx
---
Renamed `Products` section on the header to `Merchandise`
---
What we had listed on the 'products' page before was our merchandise, which is wrong. Hence renamed it to merchandise.
- Updated `src/constants/Header.ts`
- Updated `src/pages/Products.tsx`
Tested to check if the changes are reflected. It works.
=> Renamed Products to Merchandise

src/constants/MarkdownFiles/posts/gsoc-25-AdityaKrSingh26-week01.md
---
about: Weekly Blog for GSoC'25
---
This pull request adds the GSoC ’25 Week 01 blog update by Aditya Kumar Singh. The blog covers progress made on the Sugarizer 3D Human Activity project. It highlights completed goals, key technical changes, challenges faced, and learnings from the development process.
- Added a file : `src\constants\MarkdownFiles\posts\gsoc-25-AdityaKrSingh26-week01.md`
- Added a new blog post titled: GSoC ’25 Week 01 Update by Aditya Kumar Singh
- Please confirm that the metadata aligns with the blog system’s parsing requirements.
- Feedback on content clarity and structure is welcome.
---
📚 See [contributing …
=> GSoC ’25 Week 01 Update by Aditya Kumar Singh

src/constants/MarkdownFiles/posts/gsoc-25-AdityaKrSingh26-week02.md
---
---
This pull request adds the GSoC ’25 Week 02 blog update by Aditya Kumar Singh. The blog details the progress made on the Sugarizer 3D Human Body Activity project during the second week of GSoC 2025. It covers technical enhancements, such as anatomical model integration, mesh merging, and interactive feature development for the paint activity.
- Added a file : src\constants\MarkdownFiles\posts\gsoc-25-AdityaKrSingh26-week02.md
- Added a new blog post titled: GSoC ’25 Week 02 Update by Aditya Kumar Singh
---
🙋🏾🙋🏼 Questions: …
=> GSoC ’25 Week 02 Update by Aditya Kumar Singh

src/constants/MarkdownFiles/posts/gsoc-25-Nikhil-Bhatt-week01.md
---
---
Reporting work I did during Week 01
Added `gsoc-25-nikhil-bhatt-week01.md`
=> Gsoc week 01 nikhil bhatt

src/constants/MarkdownFiles/posts/gsoc-25-omsuneri-week01.md
**Reporting Period:** 2025-06-02 - 2025-06-07  
---
- **Goal 1:** To refine the JSON to text convertor code.
- **Goal 2:** To convert the convertor's Javascript code to Python.
- **Goal 3:** To create a basic Streamlit debugger app UI.
---
1. **JSON to Text Converter Refinement**  
- I focused on refining the JSON to Text Converter for Music Blocks. I improved the metadata representation of the "start" block to make it more accurate and readable in the text format. Additionally, I added …
=> Om Santosh Suneri GSoC'25 Week 01 report 

src/constants/MarkdownFiles/posts/gsoc-25-SafwanSayeed-week01.md
Here is the Update for the 1st week GSoC coding period.
=> Week 1 Update Blog By Safwan Sayeed on GSoC Project: MBv4 Program Engine

src/constants/MarkdownFiles/posts/ssoc-2025-MuhammadHaroon-week01.md
@pikurasa Can you please review it?
=> SSoC' 25 blog post for week 01 by Muhammad Haroon

src/constants/MarkdownFiles/posts/dmp-25-AnvitaPrasad-week01.md
=> Anvita Prasad DMP'25 Week 01 report

src/constants/MarkdownFiles/posts/gsoc-25-SaumyaShahi-week01.md
Added the blog post report for GSoC Week 01 progress for the Masonry Module project.  
This report includes work done on SVG-based brick rendering, configuration mapping, and dynamic rendering logic implementation.
=> Saumya Shahi - GSoC Week 01 Report: Masonry Module

src/constants/MarkdownFiles/posts/dmp-25-justin212407-week01.md
DMP 25 Week 1 Update for Masonry Module
=> Dmp 25 Week 1 Update by Justin Charles

src/constants/MarkdownFiles/posts/dmp-25-AnvitaPrasad-week01.md, src/constants/MarkdownFiles/posts/dmp-25-justin212407-week01.md
@sa-fw-an added c4gt_DMP image to blogs of DMP contributors.
=> Fix: add c4gt_DMP image in blogs of DMP mentees

src/constants/MarkdownFiles/posts/2025-06-10-gsoc-25-AdityaKrSingh26-week04.md
This pull request adds the GSoC ’25 Week 04 blog update by Aditya Kumar Singh. The blog details the progress made on the Sugarizer 3D Human Body Activity project during the second week of GSoC 2025.
---
=> GSoC ’25 Week 04 Update by Aditya Kumar Singh

src/constants/MarkdownFiles/posts/2025-06-20-gsoc-25-AdityaKrSingh26-week06.md
This pull request adds the GSoC ’25 Week 06 blog update by Aditya Kumar Singh. The blog details the progress made on the Sugarizer 3D Human Body Activity project during the 6th week of GSoC 2025.
---
=> GSoC ’25 Week 06 Update by Aditya Kumar Singh

src/constants/MarkdownFiles/posts/2025-06-22-gsoc-25-saumya-week03.md
This pull request adds the GSoC 2025 Week 03 progress report for Saumya Shahi, working on the Masonry Module of Music Blocks v4. The report outlines the implementation of a brick tree model that supports hierarchical and graph-like connections, along with comprehensive tree management and validation mechanisms.
=> Add GSoC week-3 progress report for saumyashahi

src/constants/MarkdownFiles/posts/2025-06-08-ssoc-2025-MuhammadHaroon-week01.md, src/constants/MarkdownFiles/posts/2025-06-15-ssoc-2025-MuhammadHaroon-week02.md, src/constants/MarkdownFiles/posts/2025-06-22-ssoc-2025-MuhammadHaroon-week03.md, src/constants/MarkdownFiles/posts/2025-06-22-ssoc-2025-MuhammadHaroon.md
=> SSoC' 25 blog post for week 03 by Muhammad Haroon

src/constants/MarkdownFiles/posts/2025-06-23-dmp-25-therealharshit-week03.md
@sa-fw-an @pikurasa published week03 blog.
=> DMP '25 Week03 Update by Harshit Verma

src/constants/MarkdownFiles/posts/2025-06-22-dmp-25-AnvitaPrasad-week03.md
=> DMP '25 Week03 Update by Anvita Prasad

src/constants/MarkdownFiles/posts/2025-06-29-gsoc-25-omsuneri-week04.md
**Reporting Period:** 2025-06-22 - 2025-06-28
---
- **Goal 1:** Testing the Debugger with Intensive Prompting
- **Goal 2:** Improving the Quality of LLM Responses 
- **Goal 3:** Making the Debugger Interactive and Kid-Friendly 
---
1. **Testing the Debugger with Intensive Prompting**  
- I carried out extensive testing of the debugger by feeding it a wide range of Music Blocks projects and crafting diverse prompts to simulate how real users — especially children — might ask questions or seek …
=> GSoC'25 Week 04 updates by om santosh suneri

src/constants/MarkdownFiles/posts/2025-06-29-gsoc-25-diwangshu-week04.md
---
GSoC'25 Week-04 Update by Diwangshu Kakoty
added `2025-06-29-gsoc-25-diwangshu-week04.md`
---
---
=> GSoC'25 Week-04 Update by Diwangshu Kakoty

src/constants/MarkdownFiles/posts/2025-06-30-ssoc-2025-MuhammadHaroon-week04.md
=> SSoC' 25 blog post for week 04 by Muhammad Haroon

src/constants/MarkdownFiles/posts/2025-06-22-DMP-25-justin212407-week3.md
Week 3 DMP 2025 Blog for Masonry
=> DMP'25 Week 03 update by Justin Charles

src/components/Donation.tsx
Change the "Donate Now", "Subscribe" button cursor to pointer. And made the "Join the volunteer" button to clickable without the entire row
---
about: Change the "Donate Now", "Subscribe" button cursor to pointer. And made the "Join the volunteer" button to clickable without the entire row
---
When we hover on the "Donate Now" button in Home page the cursor is changed to pointer
When we hover on the "Subscribe" button in Home page the cursor is changed to pointer
Make the "Join the volunteer" entire row non-clickable and just made the button clickable
This PR fixes #283 
---
🙋🏾🙋🏼 Questions: …
=> Change the "Donate Now", "Subscribe" button cursor to pointer. And made the "Join the volunteer" button to clickable without the entire row

src/constants/MarkdownFiles/posts/2025-07-06-gsoc-25-Nikhil-Bhatt-week05.md
Minor improvement for https://github.com/sugarlabs/www-v2/pull/278
=> Create newlines for "Challenge" to "Solution"

src/constants/MarkdownFiles/posts/2025-07-06-gsoc-25-diwangshu-week05.md
---
GSoC'25 Week-05 Update by Diwangshu Kakoty
added `2025-07-06-gsoc-25-diwangshu-week05.md`
---
---
=> GSoC'25 Week-05 Update by Diwangshu Kakoty 

src/components/AboutUs/ProjectSection.tsx, src/components/FAQItem.tsx, src/components/TryCard.tsx, src/constants/aboutUs/navigation.ts, src/pages/About/FAQs.tsx, src/pages/Donate.tsx, src/pages/News/NewsPage.tsx, src/pages/Volunteer.tsx, src/sections/Banner.tsx
Changes all the clickable content to cursor pointer when we hover on them
---
about: Changes all the clickable content to cursor pointer when we hover on them
---
---
=> Changes all the clickable content to cursor pointer when we hover on them

src/sections/Header.tsx
---
about: All the links are properly alligned
---
All the links are properly alligned
This PR fixes #296 
All the links buttons are properly alligned 
---
=> All the links are properly alligned

src/constants/MarkdownFiles/posts/2025-07-12-gsoc-25-Elwin-Li-week06.md
---
name: GSoC'25 Week 6 Update by Elwin Li
about: week 6 blog + midterm project summary
---
---
=> GSoC'25 Week 6 Update by Elwin Li

src/constants/MarkdownFiles/posts/2025-07-05-gsoc-25-MebinThattil-week05.md
---
GSoC '25 Week 05 Report - Mebin Thattil
---
Report for week 5.
- Added `2025-07-05-gsoc-25-MebinThattil-week05.md` -> blog report
=> GSoC Week 5 report by Mebin Thattil

src/constants/MarkdownFiles/posts/2025-07-12-mostlyk-week06.md
Apologies for being late this time.
=> GSoC'25 Week 06 Update by Krish

src/constants/MarkdownFiles/posts/2025-07-20-gsoc-25-AdityaKrSingh26-week10.md
This pull request adds the GSoC ’25 Week 10 blog update by Aditya Kumar Singh. The blog details the progress made on the Sugarizer 3D Human Body Activity & Stickman Activity project during the 10th week of GSoC 2025.
---
=> GSoC ’25 Week 10 Update by Aditya Kumar Singh

src/constants/MarkdownFiles/posts/2025-07-21-dmp-25-therealharshit-week07.md
@pikurasa published week 07 blog.
=> DMP '25  Week07 update by Harshit Verma

src/constants/MarkdownFiles/posts/2025-07-14-gsoc-25-BishoyWadea-week06.md
Report for week 6.
Added 2025-07-14-gsoc-25-BishoyWadea-week06.md-> blog report
=> GSoC 25 week 6 update by Bishoy Wadea

src/constants/MarkdownFiles/posts/2025-07-13-gsoc-25-MebinThattil-week06.md, src/constants/MarkdownFiles/posts/2025-07-20-gsoc-25-MebinThattil-week07.md
---
GSoC '25 Week 07 Report - Mebin Thattil
---
Report for week 6 with Mid-Term summary.
- Modified `2025-07-13-gsoc-25-MebinThattil-week06.md` -> Added the `midterm` tag as well
- Added `2025-07-20-gsoc-25-MebinThattil-week07.md` -> Week 7 Blog
=> GSoC '25 Week 07 Report - Mebin Thattil

src/constants/MarkdownFiles/posts/2025-07-30-gsoc-25-diwangshu-week08.md
=> GSoC ’25 Week 08 Update by Diwangshu Kakoty

src/constants/MarkdownFiles/posts/2025-07-27-gsoc-25-omsuneri-week08.md
**Reporting Period:** 2025-07-21 - 2025-07-27
---
**Implement a Music Blocks-compatible UI widget for the AI Debugger with proper session tracking, error handling, and user interaction controls.**
---
This week, I focused on integrating a clean and interactive **chat-based UI debugger widget** into the Music Blocks environment. The UI is designed to give learners a smooth experience interacting with the AI assistant while also maintaining session context, error visibility, and chat history. …
=> GSoC'25 week 08 update by Om Santosh Suneri

src/constants/MarkdownFiles/posts/2025-08-04-gsoc-25-omsuneri-week09.md
**Reporting Period:** 2025-07-28 - 2025-08-03
---
The primary goal for this Week was to **embed the AI-powered Debugger directly into the Music Blocks UI** so that users, especially kids, could debug their projects *without leaving the app*. This meant replacing the previously external Streamlit interface with a fully functional, session-aware UI widget inside the Music Blocks canvas, connected to the FastAPI backend.
---
Until now, users had to export their Music Blocks project and visit an …
=> GSoC'25 Week 09 update by Om Santosh Suneri

src/constants/MarkdownFiles/posts/2025-08-02-dmp-25-therealharshit-week08.md
@pikurasa pushed week 08 blog, sorry for the delay.
=> DMP '25 Week08 update by Harshit Verma

src/constants/MarkdownFiles/posts/2025-08-03-gsoc-25-MebinThattil-week09.md
---
GSoC '25 Week 09 Report - Mebin Thattil
---
Report for week 9.
- Added `2025-08-03-gsoc-25-MebinThattil-week09.md` -> Week 9 Blog
=> GSoC Week 9 report by Mebin Thattil

src/constants/MarkdownFiles/posts/2025-08-07-gsoc-25-AdityaKrSingh26-week13.md
This pull request adds the GSoC ’25 Week 13 blog update by Aditya Kumar Singh. The blog details the progress made on the Sugarizer Stickman Activity project during the 13th week of GSoC 2025.
---
=> GSoC ’25 Week 13 Update by Aditya Kumar Singh

src/constants/MarkdownFiles/posts/2025-07-26-gsoc-25-Elwin-Li-week08.md
---
name: GSoC 25 week 8 update by Elwin Li
about: MusicBlocks generation RAG pipeline
---
---
=> GSoC 25 week 8 update by Elwin Li

src/constants/MarkdownFiles/posts/2025-07-27-gsoc-25-MebinThattil-week08.md
---
GSoC '25 Week 08 Report - Mebin Thattil
---
Report for week 8.
- Added `2025-07-27-gsoc-25-MebinThattil-week08.md` -> Week 8 Blog
=> GSoC '25 Week 08 Report - Mebin Thattil

src/constants/MarkdownFiles/posts/2025-08-09-gsoc-25-Elwin-Li-week10.md
---
name: GSoC 25 week 10 update by Elwin Li
about: Music Blocks generation widget Updates
---
---
=> GSoC 25 week 10 update by Elwin Li

src/constants/MarkdownFiles/posts/2025-08-10-gsoc-25-Nikhil-Bhatt-week10.md
Reporting the work I did for week 10
=> gsoc 25 week 10 update by Nikhil bhatt

src/constants/MarkdownFiles/posts/2025-08-14-gsoc-25-BishoyWadea-week09.md
Report for week 9.
Added 2025-08-14-gsoc-25-BishoyWadea-week09.md-> blog report
=> GSoC 25 week 9 update by Bishoy Wadea

src/constants/MarkdownFiles/posts/2025-08-10-gsoc-25-MebinThattil-week10.md
---
GSoC '25 Week 10 Report - Mebin Thattil
---
Report for week 10.
- Added `2025-08-10-gsoc-25-MebinThattil-week10.md` -> Week 10 Blog
=> GSoC Week 10 report by Mebin Thattil

src/constants/MarkdownFiles/posts/2025-08-03-ssoc-2025-MuhammadHaroon-week09.md
=> SSoC' 25 blog post for week 09 by Muhammad Haroon

src/constants/MarkdownFiles/posts/2025-08-17-gsoc-25-AdityaKrSingh26-week14.md
This pull request adds the GSoC ’25 Week 14 blog update by Aditya Kumar Singh. The blog details the progress made on the Sugarizer Stickman Activity project during the 14th week of GSoC 2025.
---
=> GSoC ’25 Week 14 Update by Aditya Kumar Singh

src/constants/MarkdownFiles/posts/2025-08-10-ssoc-2025-MuhammadHaroon-week10.md
=> SSoC' 25 blog post for week 10 by Muhammad Haroon

src/constants/MarkdownFiles/posts/2025-08-29-gsoc-25-diwangshu-week11.md
=> GSoC'25 week 11 update by Diwangshu Kakoty

src/constants/MarkdownFiles/posts/2025-08-17-ssoc-2025-MuhammadHaroon-week11.md
=> SSoC' 25 blog post for week 11 by Muhammad Haroon

src/constants/MarkdownFiles/posts/2025-08-24-ssoc-2025-MuhammadHaroon-week12.md
=> SSoC' 25 blog post for week 12 by Muhammad Haroon

src/constants/MarkdownFiles/posts/2025-09-01-gsoc-25-diwangshu-final-report.md
GSoC'25 Final Report by Diwangshu Kakoty
=> GSoC'25 Final report by Diwangshu Kakoty

src/constants/MarkdownFiles/posts/2025-08-24-gsoc-25-MebinThattil-week12.md
---
GSoC '25 Week 12 & Final Report  - Mebin Thattil
---
Report for week 12 + Final Report.
- Added `2025-08-24-gsoc-25-MebinThattil-week12.md` -> Week 12 Blog & Final Report
=> GSoC Week 12 report + Final Report by Mebin Thattil

src/constants/MarkdownFiles/posts/2025-08-30-dmp-25-therealharshit-week12.md
@pikurasa pushed week 12 blog, I'll also push my final blog soon.
=> DMP '25 Week12 update by Harshit Verma

src/constants/MarkdownFiles/posts/2025-09-09-gsoc-25-AdityaKrSingh26-week17.md
This pull request adds the GSoC’25 Week 17 blog update by Aditya Kumar Singh. The blog details the progress made on the Sugarizer Stickman Activity project during the 16th week of GSoC 2025.
---
=> GSoC ’25 Week 17 and Bug fix Update by Aditya Kumar Singh

src/constants/MarkdownFiles/posts/2025-08-21-gsoc-25-BishoyWadea-week10.md, src/constants/MarkdownFiles/posts/2025-08-25-gsoc-25-BishoyWadea-week10.md
Report for week 10.
Added 2025-08-21-gsoc-25-BishoyWadea-week010.md-> blog report
=> GSoC 25 week 10 update by Bishoy Wadea

src/constants/MarkdownFiles/posts/2025-09-12-gsoc-25-bishoy-wadea-final-report.md
Update repo links after transferring ownership to SL
Added 2025-09-12-gsoc-25-bishoy-wadea-final-report.md-> blog report
=> Final Report Submission By Bishoy Wadea

docs/dev_guide.md
Proofread and corrected grammatical issues in the Developer's Guide. Improved clarity, consistency, and professional tone while keeping all instructions and code snippets accurate.
🔗 Related Issue
Fixes #449
🔄 Type of Change
📖 Content Update (text changes, documentation)
📷 Visual Changes
None
🧪 Testing Performed
Verified instructions and code snippets remain accurate.
Checked for readability, formatting, and link correctness.
💭 Additional Notes
Documentation improvements only; no code changes included
=> fix(docs): correct grammatical errors in developer guide

README.md
Fixes: #450  
- Added exact versions for **React**, **TypeScript**, **Vite**, **Tailwind CSS**, and other key tools based on the current `package.json`.  
- Improved overall clarity and completeness of the **Tech Stack** section.  
- No changes were made to the **Aims**, **Contributing**, or **Development** sections.
=> updated README with Latest Tech Stack Information
