sugarlabs/www-v2

docs/Adding_favicon.md

This PR adds a step-by-step guide on how to add and modify favicons in the project. The `Favicon.md` file includes instructions for adding a new favicon, updating the favicon list in `Randomfavicon.js`, and modifying the colors of existing favicons by changing hex codes in the SVG files.

add favicon instruction

---

src/sections/Header.tsx

This PR fixes the navigation menu in mobile devices.

fix nav menu in lower res screens

---

src/components/Donation.tsx
src/styles/Animations.ts

---
Name: Added Subscribe Functionality.
about: In this PR I have currently added the subscribe functionality for the newsletter.
---
In the src\components\Donation.tsx I have added the logic and functionality for allowing users to subscribe to the newsletter.
This PR fixes #51 
- Change 1 in src\components\Donation.jsx I wrapped the input and button in <motion.form> tag
- Change 2 in the form tag I added action="https://buttondown.com/api/emails/embed-subscribe/sugarlabs" and method="post"
- Change 3 in the input tag I added name: email and to a required field.
- Change 4 in the submit tag I added type: submit
- ...
I tried to sign myself up and it has successfully worked
- Ran sign up test on my email
- Tested on browsers Opera GX and Edge
- ...
After multiple attempts to test the …

Added the functionality for the subscribe form

---

src/pages/Volunteer.tsx

---
name: fixed getting involved button
about: issue #143 
---
The getting involved button was not working, so as asked by @sa-fw-an changed it to "get involved" and added scrollIntoView to volunteer cards on click of the button
##After 
https://github.com/user-attachments/assets/1038d655-26d9-43c4-80e8-0b5193c00787
This PR fixes #143 
- Changed Getting involved to "Get Involved"
- Added id to volunteer cards section
- Used getElementbyId to scroll onto the volunteer cards section upon click of the button
- Tested locally.
- Ran npm run format for the file changed .
- Ran npm run build and npm run lint:ts to verify
- Tested on browsers edge, chrome, arc, brave.
- ...
📚 See [contributing …

fixed getting involved button

---

src/constants/MarkdownFiles/posts/gsoc-25-mostlyk-week01.md

Week 1 updates.
Checked on browser, seem to work!

GSoC '25 Community Bonding and First Week report by Krish

---

src/constants/MarkdownFiles/posts/gsoc-25-FirePheonix-week01.md

---
---
This PR fixes #
- Change 1
- Change 2
- ...
- Tested feature X in scenario Y.
- Ran unit tests for component Z.
- Tested on browsers A, B, and C.
- ...
---

GSoC'25 Week 01 Update by Shubham

---

src/constants/MarkdownFiles/posts/2025-06-07-gsoc-25-Elwin-Li-week01.md

---
name: Elwin Li - Week 1 GSoC report for JSeditor updates
about: week01 blog for JSeditor updates
---
---

Elwin Li - Week 1 GSoC report for JSeditor updates (was deleted)

---

src/constants/MarkdownFiles/authors/nikhil-bhatt.md
src/constants/MarkdownFiles/posts/2025-06-15-gsoc-25-Nikhil-Bhatt-week02.md

---
Gsoc 25 Week 02 Report by Nikhil Bhatt
---
Reporting the work I did during Week 02
Added  Nikhil-Bhatt as the `author`
Added `2025-06-14-gsoc-25-Nikhil-Bhatt-Week02.md`

Gsoc 25 Week 02 Update by Nikhil-Bhatt

---

src/constants/MarkdownFiles/authors/diwangshu-kakoty.md
src/constants/MarkdownFiles/posts/2025-06-08-gsoc-25-diwangshu-week01.md
src/constants/MarkdownFiles/posts/2025-06-15-gsoc-25-diwangshu-week02.md

---
GSoC' 25 Week 02 Report by Diwangshu Kakoty
---
Report for week 02
Added `gsoc-25-diwangshu-week02.md` 
Added `diwangshu-kakoty.md`
Updated `gsoc-25-diwangshu-week01.md` format according to the new template

GSoC '25 Week 02 Update by Diwangshu Kakoty

---

src/constants/MarkdownFiles/posts/2025-06-15-ssoc-2025-MuhammadHaroon-week02.md

SSoC' 25 blog post for week 02 by Muhammad Haroon

---

src/constants/MarkdownFiles/authors/justin-charles.md
src/constants/MarkdownFiles/posts/2025-06-15-dmp-25-justin212407-week02.md

This PR adds Week 2 Blog for DMP'25 for MusicBlocks-v4 Masonry Module and adds Justin Charles as author

DMP '25 Week02 Update by Justin Charles 

---

src/constants/MarkdownFiles/authors/amannaik247.md
src/constants/MarkdownFiles/posts/2025-06-08-dmp-25-AmanNaik-week01.md

DMP 25 week 01 blog by Aman Naik

---

src/constants/MarkdownFiles/posts/2025-06-14-gsoc-25-saumya-week02.md

This commit updates the blog post frontmatter to correctly reference the author file:
- Changed `author` from `saumyashahi.md` to `saumya-shahi.md` to match the actual path.
- Ensures the author metadata renders properly on the GSoC blog post page.
Tested locally and verified metadata displays as expected.

Fix author file path for Saumya Shahi in blog post

---

src/constants/MarkdownFiles/posts/2025-06-21-gsoc-25-MebinThattil-week03.md

---
GSoC '25 Week 03 Report - Mebin Thattil
---
Report for week 3.
- Added `2025-06-21-gsoc-25-MebinThattil-week03.md` -> blog report

GSoC Week 3 report by Mebin Thattil

---

src/constants/MarkdownFiles/authors/nikhil-bhatt.md
src/constants/MarkdownFiles/posts/2025-06-22-gsoc-25-Nikhil-Bhatt-week03.md

Reporting the work I did during Week 02
- Added `2025-06-22-gsoc-25-Nikhil-Bhatt-week03.md`
-  Changed authors/nikhil-bhatt with the changes suggested in the last PR.

Gsoc 25 Week 03 Update by Nikhil-Bhatt

---

src/constants/MarkdownFiles/posts/2025-06-22-gsoc-25-SafwanSayeed-week03.md

This is a Blog Post for the work done in week 3 of GSoC'25 By Safwan Sayeed for the Project `Music Blocks 4 Program Engine `

GSoC'25 Week 3 Blog Post By Safwan Sayeed

---

src/constants/MarkdownFiles/posts/2025-06-30-gsoc-25-AdityaKrSingh26-week07.md

This pull request adds the GSoC ’25 Week 07 blog update by Aditya Kumar Singh. The blog details the progress made on the Sugarizer 3D Human Body Activity project during the 7th week of GSoC 2025.
---

GSoC ’25 Week 07 Update by Aditya Kumar Singh

---

src/constants/MarkdownFiles/posts/dmp-25-AnvitaPrasad-week05.md

DMP'25 Week-05 Blog Post by Anvita Prasad

DMP'25 Week-05 Update by Anvita Prasad

---

src/constants/MarkdownFiles/posts/2025-07-13-gsoc-25-omsuneri-week06.md

**Reporting Period:** 2025-07-06 - 2025-07-12
---
**Build a tightly integrated debugging experience by embedding the JSON-to-Text converter into the main debugger Streamlit app and enabling users to export complete chat logs with the AI assistant**
---
This week’s focus was two-fold:
1. **Merge and integrate** the Music Blocks JSON-to-Text converter directly into the existing Streamlit-based debugger UI.
2. **Enhance user experience** by introducing a "Chat Export" feature that allows users …

Week 06 update by Om Santosh Suneri GSoC'25

---

src/constants/MarkdownFiles/posts/2025-07-15-gsoc-25-AdityaKrSingh26-week09.md

This pull request adds the GSoC ’25 Week 09 and Midterm blog update by Aditya Kumar Singh. The blog details the progress made on the Sugarizer 3D Human Body Activity & Stickman Activity project during the 9th week of GSoC 2025 and Progress made in GSoC'25 till now.
---

GSoC ’25 Week 09 and Midterm Summary Update by Aditya Kumar Singh

---

src/constants/MarkdownFiles/posts/2025-07-20-gsoc-25-Nikhil-Bhatt-week07.md

Blog on the work I did during week 7 of GSoC 25
- Added `2025-07-20-gsoc-25-nikhil-bhatt-week07.md`

gsoc 25 week 07 update by Nikhil

---

src/pages/News/NewsPage.tsx

This PR fixes the yellow notification badge on the "Load More Articles" Button and allowed it to overflow to look better.
fixes #344
Screenshot of button after fix:

fix #344: the notification badge made unclipped

---

src/constants/MarkdownFiles/posts/2025-08-17-gsoc-25-omsuneri-week11.md

**Reporting Period:** 2025-08-11 - 2025-08-17
---
**Finalize and polish the entire AI debugger stack (frontend + backend) to make it production-ready and suitable for upstream merge.**
---
This week, my main focus was on **refining the entire debugger system** to ensure it is **production-ready** and can be safely merged upstream. I worked on polishing both the **frontend widget code** and the **FastAPI backend**, improving code structure, adding helpful logs for developers, handling errors …

GSoC’25 Week 11 Update by Om Santosh Suneri

---

src/pages/News/NewsPage.tsx

This PR adds a clear button to the News page search input.  
Currently, users have to manually backspace to remove their search term. With this change, they can clear the input in one click.
Fixes #418

Clear search button

---

src/pages/News/NewsDetailPage.tsx
src/pages/News/NewsPage.tsx

Fixed an issue where the selected category was lost when navigating back from an article page.
Now, the user is returned to the same category (e.g., Community News, Developer News) with any search query preserved.
Fixes #424

fixed category navigation

---

src/constants/MarkdownFiles/posts/2025-08-28-gsoc-25-BishoyWadea-week11.md

Report for week 11.
Added 2025-08-28-gsoc-25-BishoyWadea-week011.md-> blog report

GSoC 25 week 11 update by Bishoy Wadea

---

src/constants/MarkdownFiles/posts/2025-09-04-gsoc-25-BishoyWadea-week12.md

Report for week 12.
Added 2025-09-04-gsoc-25-BishoyWadea-week012.md-> blog report

GSoC 25 week 12 update by Bishoy Wadea

---

docs/dev_guide.md

This PR proofreads and fixes grammatical errors in the Sugar Labs `dev_guide` for clarity and readability.
- Addresses #449
- Fixed commas, semicolons, and spacing
- Polished wording while keeping all _italic_ and **bold** formatting
- Verified technical instructions remain accurate
- Markdown renders correctly; all links work
- No code or build changes
- While editing, noticed duplicate npm run build instructions— comment added to PR for clarification.

Fix grammar and clarity in dev_guide (#449)

---

src/components/shared/DarkModeToggle.tsx

This PR updates the **Dark Mode Toggle** component with a modern, animated design using the `lucide-react` Sun and Moon icons. The toggle now features:
* Smooth animated transitions between light and dark modes.
* Hover effects with subtle scaling and shadow changes for better interactivity.
* Improved visual styling for light and dark modes, including gradient backgrounds and thumb effects.
* Accessibility enhancements with proper ARIA attributes.
These changes enhance the UI/UX, making the dark mode toggle more intuitive and visually appealing.
---
Fixes #470 
---
---
Light Mode Toggle
Dark Mode Toggle
Video
https://github.com/user-attachments/assets/d832cc49-de54-4f99-b2ce-b44d5e1cd677
Mobile View
---
1. Switching between light and dark modes updates the DOM and localStorage correctly. …

changed ui for mode toggle

---

src/components/AboutUs/RoadmapSection.tsx

The text in the "Our Strategy" section is visible and readable in both light and dark modes.
fixes: #477

Fixed the visiblity issue in about us page
